name: Devops project 5

on: push
jobs:
  devops-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependcies
        run: pip install -r requirements.txt
     
      - name: Code formatting 
        run: black .
    
      - name: Lint test
        run: flake88888888 .
   
      - name: Static analysis
        run: bandit . -r 
